version: '3'
services:
  keyvalueone:
    build: ../key-value-service/.
    ports:
      - "8080:8080"
  keyvaluetwo:
    build: ../key-value-service/.
    ports:
      - "9090:8080"
  keyvaluethree:
    build: ../key-value-service/.
    ports:
      - "7070:8080"